// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk3uLqL41QN89UJIp75p45VpKGNLfbxOg',
    appId: '1:209171007962:web:453e0c610ff60131e058e3',
    messagingSenderId: '209171007962',
    projectId: 'proyecto-fdw',
    authDomain: 'proyecto-fdw.firebaseapp.com',
    storageBucket: 'proyecto-fdw.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBZu7JdQPopyqO05E2tSSCDde0zAr1Of0',
    appId: '1:209171007962:android:7f87cddc4cfe6f97e058e3',
    messagingSenderId: '209171007962',
    projectId: 'proyecto-fdw',
    storageBucket: 'proyecto-fdw.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Scpp1KGxPROlRh7pXYdBwYzKUdIzExQ',
    appId: '1:209171007962:ios:5c9b70e5f4382ac1e058e3',
    messagingSenderId: '209171007962',
    projectId: 'proyecto-fdw',
    storageBucket: 'proyecto-fdw.appspot.com',
    iosClientId: '209171007962-q1hugrrfj8ksqmlporm9h3023mrs4n2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocDeIdeas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6Scpp1KGxPROlRh7pXYdBwYzKUdIzExQ',
    appId: '1:209171007962:ios:1c53a2f1884d469de058e3',
    messagingSenderId: '209171007962',
    projectId: 'proyecto-fdw',
    storageBucket: 'proyecto-fdw.appspot.com',
    iosClientId: '209171007962-v3m7420oqksplu9utrb4hsn6j0sl3bon.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocDeIdeas.RunnerTests',
  );
}
